################################################################################
#
# esp-hosted-fork
#
################################################################################

ESP_HOSTED_FORK_VERSION = f1c200s
ESP_HOSTED_FORK_SITE = $(BR2_EXTERNAL)/package/esp-hosted-fork/esp-hosted
ESP_HOSTED_FORK_DEPENDENCIES = linux
ESP_HOSTED_FORK_LICENSE = GPL-2.0
ESP_HOSTED_FORK_LICENSE_FILE = LICENSE
ESP_HOSTED_FORK_MODULE_SUBDIRS = esp_hosted_ng/host
ESP_HOSTED_FORK_SITE_METHOD = local

define ESP_HOSTED_FORK_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_NET)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_CFG80211)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211)
	$(call KCONFIG_ENABLE_OPT,CONFIG_BT)
	$(if $(BR2_PACKAGE_ESP_HOSTED_FORK_SPI),
		$(call KCONFIG_ENABLE_OPT,CONFIG_SPI),
		$(call KCONFIG_ENABLE_OPT,CONFIG_MMC))
endef

ifeq ($(BR2_PACKAGE_ESP_HOSTED_FORK_SPI),y)
ESP_HOSTED_FORK_MODULE_MAKE_OPTS = target=spi
else
ESP_HOSTED_FORK_MODULE_MAKE_OPTS = target=sdio
endif

ifeq ($(BR2_PACKAGE_ESP_HOSTED_FORK_TARGET_ESP32),y)
ESP_HOSTED_FORK_MODULE_MAKE_OPTS += ESP_SLAVE=CONFIG_TARGET_ESP32=y
else
ESP_HOSTED_FORK_MODULE_MAKE_OPTS += ESP_SLAVE=CONFIG_TARGET_ESP32C6=y
endif

$(eval $(kernel-module))
$(eval $(generic-package))
